@startuml
class "Algorithm::Algorithm<GUIAlgorithm,AnimationState>" as C_0001424751178677964674
class C_0001424751178677964674 {
+Algorithm<GUIAlgorithm, AnimationState>() : void
+Algorithm<GUIAlgorithm, AnimationState>() : void
+~Algorithm<GUIAlgorithm, AnimationState>() : void
+Empty() : void
+Random() : void
+RandomFixedSize() : void
+UserDefined() : void
+ReadFromExternalFile() : void
+ApplyInput() : void
}
class "Algorithm::DoublyLinkedList" as C_0000297624194443678356
class C_0000297624194443678356 {
+DoublyLinkedList() : void
+DoublyLinkedList() : void
+~DoublyLinkedList() : void
+size() const : std::size_t
+InsertHead() : void
+InsertAfterTail() : void
+InsertMiddle() : void
+DeleteHead() : void
+DeleteTail() : void
+DeleteMiddle() : void
+Update() : void
+Search() : void
{static} +maxN : const int
}
class "Algorithm::CircularLinkedList" as C_0001316228858141867724
class C_0001316228858141867724 {
+CircularLinkedList() : void
+CircularLinkedList() : void
+~CircularLinkedList() : void
+size() const : std::size_t
+InsertHead() : void
+InsertAfterTail() : void
+InsertMiddle() : void
+DeleteHead() : void
+DeleteTail() : void
+DeleteMiddle() : void
+Update() : void
+Search() : void
{static} +maxN : const int
}
class "Algorithm::DynamicArray" as C_0001910196305448629698
class C_0001910196305448629698 {
+DynamicArray() : void
+DynamicArray() : void
+~DynamicArray() : void
+size() const : std::size_t
+Push() : void
+PushBack() : void
+Remove() : void
+PopBack() : void
+Update() : void
+Access() : void
+Search() : void
{static} +maxN : const int
}
class "Algorithm::StaticArray" as C_0000116177827015732116
class C_0000116177827015732116 {
+StaticArray() : void
+StaticArray() : void
+~StaticArray() : void
+size() const : std::size_t
+Insert() : void
+Delete() : void
+Update() : void
+Access() : void
+Search() : void
{static} +maxN : const int
}
class "Algorithm::Queue" as C_0001007962544806062169
class C_0001007962544806062169 {
+Queue() : void
+Queue() : void
+~Queue() : void
+size() const : std::size_t
+EnqueueEmpty() : void
+Enqueue() : void
+Dequeue() : void
+PeekFront() : void
+PeekBack() : void
{static} +maxN : const int
}
class "Algorithm::SinglyLinkedList" as C_0000879912397574858539
class C_0000879912397574858539 {
+SinglyLinkedList() : void
+SinglyLinkedList() : void
+~SinglyLinkedList() : void
+size() const : std::size_t
+InsertHead() : void
+InsertAfterTail() : void
+InsertMiddle() : void
+DeleteHead() : void
+DeleteTail() : void
+DeleteMiddle() : void
+Update() : void
+Search() : void
{static} +maxN : const int
}
class "Algorithm::Stack" as C_0000594796535729709853
class C_0000594796535729709853 {
+Stack() : void
+Stack() : void
+~Stack() : void
+size() const : std::size_t
+Push() : void
+Pop() : void
+Peek() : void
{static} +maxN : const int
{static} +mStackOrientation : const Orientation
}

'Generated with clang-uml, version 0.3.4
'LLVM version clang version 15.0.7 (https://github.com/llvm/llvm-project.git 8dfdcc7b7bf66834a761bd8de445840ef68e4d1a)
@enduml
